<?php

/**
 * @file
 * Main hooks and API functions for BAT Event State Constraints module.
 */

module_load_include('inc', 'bat_event_state_constraints', 'bat_event_state_constraints.field');

define('BAT_EVENT_STATE_CONSTRAINTS_MUST_START', 'must');
define('BAT_EVENT_STATE_CONSTRAINTS_IF_STARTS', 'if');
define('BAT_EVENT_STATE_CONSTRAINTS_NO_DAY', 'none');

use Roomify\Bat\Unit\Unit;
use Roomify\Bat\Constraint\MinMaxDaysConstraint;
use Roomify\Bat\Constraint\CheckInDayConstraint;

/**
 * Implements hook_menu().
 */
function bat_event_state_constraints_menu() {
  $items['bat_event_state_constraints/ajax'] = array(
    'title' => 'Remove item callback',
    'page callback' => 'bat_event_state_constraints_remove_js',
    'delivery callback' => 'ajax_deliver',
    'access callback' => TRUE,
    'theme callback' => 'ajax_base_page_theme',
    'type' => MENU_CALLBACK,
    'file path' => 'includes',
    'file' => 'form.inc',
  );

  return $items;
}

/**
 * Page callback to handle AJAX for removing a bat event state range item.
 *
 * This is a direct page callback. The actual job of deleting the item is
 * done in the submit handler for the button, so all we really need to
 * do is process the form and then generate output. We generate this
 * output by doing a replace command on the id of the entire form element.
 */
function bat_event_state_constraints_remove_js() {
  // drupal_html_id() very helpfully ensures that all html IDS are unique
  // on a page. Unfortunately what it doesn't realize is that the IDs
  // we are generating are going to replace IDs that already exist, so
  // this actually works against us.
  if (isset($_POST['ajax_html_ids'])) {
    unset($_POST['ajax_html_ids']);
  }

  list($form, $form_state, $form_id, $form_build_id, $commands) = ajax_get_form();
  drupal_process_form($form['#form_id'], $form, $form_state);

  // Get the information on what we're removing.
  $button = $form_state['triggering_element'];
  // Go two levels up in the form, to the whole widget.
  $element = drupal_array_get_nested_value($form, array_slice($button['#array_parents'], 0, -3));
  // Now send back the proper AJAX command to replace it.
  $commands[] = ajax_command_replace('#' . $element['#id'], drupal_render($element));
  $return = array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );

  // Because we're doing this ourselves, messages aren't automatic. We have
  // to add them.
  $messages = theme('status_messages');
  if ($messages) {
    $return['#commands'][] = ajax_command_prepend('#' . $element['#id'], $messages);
  }

  return $return;
}

/**
 * Adds the default Event state range field to certain bundle.
 */
function bat_event_state_constraints_add_event_state_range_field($bundle) {
  field_info_cache_clear();

  // Create field ('bat_constraint_range') if not exists.
  if (field_read_field('bat_constraints_range') === FALSE) {
    $field = array(
      'field_name' => 'bat_constraints_range',
      'type' => 'bat_event_state_constraints_range',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
    );
    field_create_field($field);
  }

  field_cache_clear();

  if (field_read_instance('bat_type', 'bat_constraints_range', $bundle) === FALSE) {
    // Create the instance on the bundle.
    $instance = array(
      'field_name' => 'bat_constraints_range',
      'entity_type' => 'bat_type',
      'label' => 'Event state ranges',
      'bundle' => $bundle,
      'required' => FALSE,
      'widget' => array(
        'type' => 'bat_event_state_constraints_range',
      ),
    );
    field_create_instance($instance);
  }
}

/**
 * Implements hook_entity_insert().
 */
function bat_event_state_constraints_entity_insert($entity, $type) {
  if ($type == 'bat_type_bundle') {
    bat_event_state_constraints_add_event_state_range_field($entity->type);
  }
}

/**
 * Implements hook_element_info().
 */
function bat_event_state_constraints_element_info() {
  $elements = array();
  $elements['bat_event_state_range'] = array(
    '#input' => TRUE,
    '#process' => array('bat_event_state_range_process'),
  );
  return $elements;
}

/**
 * Generates the 'bat_event_state_range' Form API element.
 */
function bat_event_state_range_process($element, $form_state, $complete_form) {
  $range = bat_date_range_fields();

  $always_id = drupal_html_id('bat-constraints-range-always');
  $constraint_type_id = drupal_html_id('bat-constraints-range-type');

  $delta = $element['#delta'];

  $element['group_conditions'] = array(
    '#type' => 'container',
    '#prefix' => '<div id="group-conditions-' . $delta . '">',
    '#suffix' => '</div>',
  );

  $element['group_conditions']['operation'] = array(
    '#type' => 'hidden',
    '#value' => (isset($element['#value']['group_conditions']['operation'])) ? $element['#value']['group_conditions']['operation'] : 0,
  );

  if (isset($form_state['input']['_triggering_element_value'])) {
    if ($form_state['input']['_triggering_element_value'] == t(variable_get('bat_event_state_min_max', 'Set min/max period'))) {
      $element['group_conditions']['operation']['#value'] = 1;
    }
    elseif ($form_state['input']['_triggering_element_value'] == t(variable_get('bat_event_state_start_day', 'Set event start day'))) {
      $element['group_conditions']['operation']['#value'] = 2;
    }
  }

  if (!empty($element['#value']) && !isset($element['#value']['group_conditions'])) {
    if ($element['#value']['constraint_type'] == BAT_EVENT_STATE_CONSTRAINTS_MUST_START) {
      $element['group_conditions']['operation']['#value'] = 2;
    }
    else {
      $element['group_conditions']['operation']['#value'] = 1;
    }
  }

  $element['group_conditions']['add_min_max'] = array(
    '#type' => 'button',
    '#value' => t(variable_get('bat_event_state_min_max', 'Set min/max period')),
    '#ajax' => array(
      'wrapper' => 'group-conditions-' . $delta,
      'callback' => 'bat_event_state_range_form_ajax_callback',
    ),
    '#submit' => array('bat_event_state_range_form_ajax_callback'),
    '#validate' => array(),
    '#limit_validation_errors' => array(),
    '#executes_submit_callback' => FALSE,
    '#name' => 'add_min_max_' . $delta,
  );

  $element['group_conditions']['add_checkin_day'] = array(
    '#type' => 'button',
    '#value' => t(variable_get('bat_event_state_start_day', 'Set event start day')),
    '#ajax' => array(
      'wrapper' => 'group-conditions-' . $delta,
      'callback' => 'bat_event_state_range_form_ajax_callback',
    ),
    '#submit' => array('bat_event_state_range_form_ajax_callback'),
    '#validate' => array(),
    '#limit_validation_errors' => array(),
    '#executes_submit_callback' => FALSE,
    '#name' => 'add_checkin_day_' . $delta,
  );

  if ($element['group_conditions']['operation']['#value'] != 0) {
    $element['group_conditions']['add_min_max']['#prefix'] = '<div style="display: none;">';
    $element['group_conditions']['add_min_max']['#suffix'] = '</div>';

    $element['group_conditions']['add_checkin_day']['#prefix'] = '<div style="display: none;">';
    $element['group_conditions']['add_checkin_day']['#suffix'] = '</div>';
  }

  if ($element['group_conditions']['operation']['#value'] == 1) {
    $element['group_conditions']['title'] = array(
      '#markup' => '<div class="condition-title"><strong>' . t(variable_get('bat_event_state_require_that', 'Require that')) . '</strong></div>',
    );

    $element['group_conditions']['minimum_stay'] = array(
      '#type' => 'checkbox',
      '#title' => t(variable_get('bat_event_state_minimum_stay', 'Minimum Event Length is')),
      '#size' => 2,
      '#ajax' => array(
        'wrapper' => 'group-conditions-' . $delta,
        'callback' => 'bat_event_state_range_form_ajax_callback',
      ),
      '#prefix' => '<div class="group-conditions-minimum-stay">',
      '#suffix' => '</div>',
      '#default_value' => (isset($element['#value']['minimum_stay']) && !empty($element['#value']['minimum_stay'])) ? 1 : 0,
    );

    if ( (isset($element['#value']['group_conditions']['minimum_stay']) &&
          $element['#value']['group_conditions']['minimum_stay'] == 1) ||
          (isset($element['#value']['minimum_stay'])) ) {

      $element['group_conditions']['minimum_stay_nights'] = array(
        '#type' => 'textfield',
        '#field_suffix' => t(variable_get('bat_event_state_days', 'days')),
        '#size' => 3,
        '#required' => TRUE,
        '#prefix' => '<div class="group-conditions-minimum-stay-nights">',
        '#suffix' => '</div>',
        '#default_value' => (isset($element['#value']['minimum_stay']) && !empty($element['#value']['minimum_stay'])) ? $element['#value']['minimum_stay'] : '',
      );
    }

    $element['group_conditions']['maximum_stay'] = array(
      '#type' => 'checkbox',
      '#title' => t(variable_get('bat_event_state_maximum_stay', 'Maximum Event Length is')),
      '#size' => 2,
      '#ajax' => array(
        'wrapper' => 'group-conditions-' . $delta,
        'callback' => 'bat_event_state_range_form_ajax_callback',
      ),
      '#prefix' => '<div class="group-conditions-maximum-stay">',
      '#suffix' => '</div>',
      '#default_value' => (isset($element['#value']['maximum_stay']) && !empty($element['#value']['maximum_stay'])) ? 1 : 0,
    );

    if ( (isset($element['#value']['group_conditions']['maximum_stay']) &&
          $element['#value']['group_conditions']['maximum_stay'] == 1) ||
          (isset($element['#value']['maximum_stay'])) ) {

      $element['group_conditions']['maximum_stay_nights'] = array(
        '#type' => 'textfield',
        '#field_suffix' => t(variable_get('bat_event_state_days', 'days')),
        '#size' => 3,
        '#required' => TRUE,
        '#prefix' => '<div class="group-conditions-maximum-stay-nights">',
        '#suffix' => '</div>',
        '#default_value' => (isset($element['#value']['maximum_stay']) && !empty($element['#value']['maximum_stay'])) ? $element['#value']['maximum_stay'] : '',
      );
    }

    $element['group_conditions']['period'] = array(
      '#title' => t(variable_get('bat_event_state_applicable', 'applicable')),
      '#type' => 'select',
      '#options' => array('always' => t(variable_get('bat_event_state_always', 'Always')), 'dates' => t(variable_get('bat_event_state_select_period', 'Select period'))),
      '#ajax' => array(
        'wrapper' => 'group-conditions-' . $delta,
        'callback' => 'bat_event_state_range_form_ajax_callback',
      ),
      '#prefix' => '<div class="group-conditions-period">',
      '#suffix' => '</div>',
      '#default_value' => (isset($element['#value']['always']) && !$element['#value']['always']) ? 'dates' : 'always',
    );

    if ( (isset($element['#value']['group_conditions']['period']) &&
          $element['#value']['group_conditions']['period'] == 'dates') ||
          (isset($element['#value']['always']) && !$element['#value']['always']) ) {

      $element['group_conditions']['start_date'] = array(
        '#title' => t(variable_get('bat_event_state_start_date', 'Start date')),
        '#required' => TRUE,
        '#default_value' => (isset($element['#value']['start_date']) && empty($element['#value']['always'])) ? $element['#value']['start_date'] : '',
        '#states' => array(
          'visible' => array(
            '#' . $always_id . ' input' => array('checked' => FALSE),
          ),
        ),
      ) + $range['bat_start_date'];

      $element['group_conditions']['end_date'] = array(
        '#title' => t(variable_get('bat_event_state_end_date', 'End date')),
        '#required' => TRUE,
        '#default_value' => (isset($element['#value']['end_date']) && empty($element['#value']['always'])) ? $element['#value']['end_date'] : '',
        '#states' => array(
          'visible' => array(
            '#' . $always_id . ' input' => array('checked' => FALSE),
          ),
        ),
      ) + $range['bat_end_date'];
    }

    $element['group_conditions']['booking_if_start'] = array(
      '#type' => 'checkbox',
      '#title' => t(variable_get('bat_event_state_booking_if_start', 'Only if event starts on a specific day')),
      '#ajax' => array(
        'wrapper' => 'group-conditions-' . $delta,
        'callback' => 'bat_event_state_range_form_ajax_callback',
      ),
      '#prefix' => '<div class="group-conditions-booking-if-start">',
      '#suffix' => '</div>',
      '#default_value' => (isset($element['#value']['constraint_type']) && $element['#value']['constraint_type'] == BAT_EVENT_STATE_CONSTRAINTS_IF_STARTS) ? 1 : 0,
    );

    if ( (isset($element['#value']['group_conditions']['booking_if_start']) &&
          $element['#value']['group_conditions']['booking_if_start'] == '1') ||
          (isset($element['#value']['start_day'])) ) {

      $element['group_conditions']['booking_if_start_day'] = array(
        '#type' => 'select',
        '#options' => bat_event_state_constraints_weekdays(),
        '#default_value' => (isset($element['#value']['start_day']) && !empty($element['#value']['start_day'])) ? $element['#value']['start_day'] : '',
      );
    }
  }
  elseif ($element['group_conditions']['operation']['#value'] == 2) {
    $element['group_conditions']['title'] = array(
      '#markup' => '<div class="condition-title"><strong>' . t(variable_get('bat_event_state_require_that', 'Require that')) . '</strong></div>',
    );

    $element['group_conditions']['booking_must_start'] = array(
      '#type' => 'select',
      '#options' => bat_event_state_constraints_weekdays(),
      '#field_prefix' => t(variable_get('bat_event_state_booking_must_start', 'Event start day must be')),
      '#prefix' => '<div class="group-conditions-booking-must-start">',
      '#suffix' => '</div>',
      '#default_value' => (isset($element['#value']['start_day']) && !empty($element['#value']['start_day'])) ? $element['#value']['start_day'] : '',
    );

    $element['group_conditions']['period'] = array(
      '#title' => t(variable_get('bat_event_state_applicable', 'applicable')),
      '#type' => 'select',
      '#options' => array('always' => t(variable_get('bat_event_state_always', 'Always')), 'dates' => t(variable_get('bat_event_state_select_period', 'Select period'))),
      '#ajax' => array(
        'wrapper' => 'group-conditions-' . $delta,
        'callback' => 'bat_event_state_range_form_ajax_callback',
      ),
      '#prefix' => '<div class="group-conditions-period">',
      '#suffix' => '</div>',
      '#default_value' => (isset($element['#value']['always']) && !$element['#value']['always']) ? 'dates' : 'always',
    );

    if ( (isset($element['#value']['group_conditions']['period']) &&
          $element['#value']['group_conditions']['period'] == 'dates') ||
          (isset($element['#value']['always']) && !$element['#value']['always']) ) {

      $element['group_conditions']['start_date'] = array(
        '#title' => t(variable_get('bat_event_state_start_date', 'Start date')),
        '#required' => TRUE,
        '#default_value' => (isset($element['#value']['start_date']) && empty($element['#value']['always'])) ? $element['#value']['start_date'] : '',
        '#states' => array(
          'visible' => array(
            '#' . $always_id . ' input' => array('checked' => FALSE),
          ),
        ),
      ) + $range['bat_start_date'];

      $element['group_conditions']['end_date'] = array(
        '#title' => t(variable_get('bat_event_state_end_date', 'End date')),
        '#required' => TRUE,
        '#default_value' => (isset($element['#value']['end_date']) && empty($element['#value']['always'])) ? $element['#value']['end_date'] : '',
        '#states' => array(
          'visible' => array(
            '#' . $always_id . ' input' => array('checked' => FALSE),
          ),
        ),
      ) + $range['bat_end_date'];
    }
  }

  $element['#element_validate'][] = 'bat_event_state_range_validate';

  return $element;
}

/**
 * Ajax callback for bat_event_state_range Form API element.
 */
function bat_event_state_range_form_ajax_callback($form, &$form_state) {
  $parents = $form_state['triggering_element']['#parents'];
  array_pop($parents);

  return drupal_array_get_nested_value($form, $parents);
}

/**
 * Validation callback for bat_event_state_range Form API element.
 */
function bat_event_state_range_validate($element, &$form_state) {
  if (isset($element['#value']['group_conditions'])) {
    if (isset($element['#value']['group_conditions']['period'])) {
      if ($element['#value']['group_conditions']['period'] == 'always') {
        $parents = array_merge($element['#parents'], array('start_date'));
        drupal_array_set_nested_value($form_state['values'], $parents, '1970-01-01', TRUE);

        $parents = array_merge($element['#parents'], array('end_date'));
        drupal_array_set_nested_value($form_state['values'], $parents, '2999-12-31', TRUE);

        $parents = array_merge($element['#parents'], array('always'));
        drupal_array_set_nested_value($form_state['values'], $parents, 1, TRUE);
      }
      elseif ($element['#value']['group_conditions']['period'] == 'dates') {
        $parents = array_merge($element['#parents'], array('group_conditions', 'start_date'));
        $start_date = drupal_array_get_nested_value($form_state['values'], $parents);

        $parents = array_merge($element['#parents'], array('group_conditions', 'end_date'));
        $end_date = drupal_array_get_nested_value($form_state['values'], $parents);

        $parents = array_merge($element['#parents'], array('start_date'));
        drupal_array_set_nested_value($form_state['values'], $parents, $start_date, TRUE);

        $parents = array_merge($element['#parents'], array('end_date'));
        drupal_array_set_nested_value($form_state['values'], $parents, $end_date, TRUE);

        $parents = array_merge($element['#parents'], array('always'));
        drupal_array_set_nested_value($form_state['values'], $parents, 0, TRUE);
      }
    }

    if ($element['#value']['group_conditions']['operation'] == 1) {
      if (isset($element['#value']['group_conditions']['booking_if_start']) && $element['#value']['group_conditions']['booking_if_start']) {
        $parents = array_merge($element['#parents'], array('constraint_type'));
        drupal_array_set_nested_value($form_state['values'], $parents, BAT_EVENT_STATE_CONSTRAINTS_IF_STARTS, TRUE);

        $start_day = isset($element['#value']['group_conditions']['booking_if_start_day']) ? $element['#value']['group_conditions']['booking_if_start_day'] : 1;

        $parents = array_merge($element['#parents'], array('start_day'));
        drupal_array_set_nested_value($form_state['values'], $parents, $start_day, TRUE);      
      }
      else {
        $parents = array_merge($element['#parents'], array('constraint_type'));
        drupal_array_set_nested_value($form_state['values'], $parents, BAT_EVENT_STATE_CONSTRAINTS_NO_DAY, TRUE);
      }

      if (isset($element['#value']['group_conditions']['minimum_stay_nights']) && $element['#value']['group_conditions']['minimum_stay_nights'] != '' && $element['#value']['group_conditions']['minimum_stay']) {
        $parents = array_merge($element['#parents'], array('minimum_stay'));
        drupal_array_set_nested_value($form_state['values'], $parents, $element['#value']['group_conditions']['minimum_stay_nights'], TRUE);
      }

      if (isset($element['#value']['group_conditions']['maximum_stay_nights']) && $element['#value']['group_conditions']['maximum_stay_nights'] != '' && $element['#value']['group_conditions']['maximum_stay']) {
        $parents = array_merge($element['#parents'], array('maximum_stay'));
        drupal_array_set_nested_value($form_state['values'], $parents, $element['#value']['group_conditions']['maximum_stay_nights'], TRUE);
      }
    }
    elseif ($element['#value']['group_conditions']['operation'] == 2) {
      $parents = array_merge($element['#parents'], array('constraint_type'));
      drupal_array_set_nested_value($form_state['values'], $parents, BAT_EVENT_STATE_CONSTRAINTS_MUST_START, TRUE);

      $parents = array_merge($element['#parents'], array('start_day'));
      drupal_array_set_nested_value($form_state['values'], $parents, $element['#value']['group_conditions']['booking_must_start'], TRUE);
    }
  }
}

/**
 * Returns weekdays keyed in N format.
 *
 * @return array
 *   The readable weekdays keyed by N format.
 */
function bat_event_state_constraints_weekdays() {
  return array(
    1 => t('Monday'),
    2 => t('Tuesday'),
    3 => t('Wednesday'),
    4 => t('Thursday'),
    5 => t('Friday'),
    6 => t('Saturday'),
    7 => t('Sunday')
  );
}

/**
 * Gives the human readable weekday given its N identifier.
 *
 * @param int $day
 *   The weekday identifier.
 * @return string
 *   The human readable weekday.
 */
function bat_event_state_constraints_get_weekday($day) {
  $weekdays = bat_event_state_constraints_weekdays();
  return isset($weekdays[$day]) ? $weekdays[$day] : '';
}

/**
 * Implements hook_bat_event_constraints_info().
 */
function bat_event_state_constraints_bat_event_constraints_info() {
  $constraints = array();

  $types = bat_unit_get_types();
  foreach ($types as $type) {
    $field_constraints = field_get_items('bat_type', $type, 'bat_constraints_range');

    if (!empty($field_constraints)) {
      $drupal_units = bat_unit_load_multiple(FALSE, array('type_id' => $type->type_id));
      $bat_units = array();
      foreach ($drupal_units as $unit_id => $unit) {
        $bat_units[] = new Unit($unit_id, 0);
      }

      foreach ($field_constraints as $field_constraint) {
        $start_date = new DateTime($field_constraint['start_date']);
        $end_date = new DateTime($field_constraint['end_date']);

        if ($field_constraint['constraint_type'] == BAT_EVENT_STATE_CONSTRAINTS_MUST_START) {
          $constraint = new CheckInDayConstraint($bat_units, $field_constraint['start_day'], $start_date, $end_date);
          $constraints[] = array(
            'type' => $type->type,
            'constraint' => $constraint,
          );
        }
        else {
          $minimum_stay = $field_constraint['minimum_stay'];
          $maximum_stay = $field_constraint['maximum_stay'];
          $start_day = $field_constraint['start_day'];

          $constraint = new MinMaxDaysConstraint($bat_units, $minimum_stay, $maximum_stay, $start_date, $end_date, $start_day);
          $constraints[] = array(
            'type' => $type->type,
            'constraint' => $constraint,
          );
        }
      }
    }
  }

  return $constraints;
}

/**
 * Implements hook_field_presave().
 */
function bat_event_state_constraints_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if ($field['type'] == 'bat_event_state_constraints_range') {
    cache_clear_all('bat_event_constraints_info', 'cache');
  }
}
